# Generated by Django 4.0 on 2022-01-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventreg',
            name='poster_link',
            field=models.URLField(default='NULL'),
        ),
    ]
