# Generated by Django 4.0 on 2022-01-21 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0003_participantreg'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipantReg',
        ),
    ]
