# Generated by Django 4.0 on 2022-01-22 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0005_participantreg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participantreg',
            old_name='select_event',
            new_name='selected_event_name',
        ),
        migrations.AddField(
            model_name='participantreg',
            name='selected_event_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
