# Generated by Django 4.0 on 2022-01-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event_App', '0006_rename_select_event_participantreg_selected_event_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=30)),
                ('contact_email', models.CharField(max_length=30)),
                ('contact_description', models.TextField()),
            ],
        ),
    ]
